### ISSUE TITLE
Your XML

### ISSUE THREAD

**Issue by orthagh** [ticgal/jsaddons#1]
Hello @OscarBeiro .

I'm currently reviewing the submited xml for this repository.

One small thing to fix:

```xml
<screenshots>
      <screenshot>https://raw.githubusercontent.com/ticgal/actualtime/multimedia/JSAddons-GLPI-Plugin-1.png</screenshot>
      <screenshot>https://raw.githubusercontent.com/ticgal/actualtime/multimedia/JSAddons-GLPI-Plugin-2.png</screenshot>
      <screenshot>https://raw.githubusercontent.com/ticgal/actualtime/multimedia/JSAddons-GLPI-Plugin-3.png</screenshot>
</screenshots>
```

The screenshots parts are 404 links, could you provide real screenshots for your plugin

**Comment by OscarBeiro** [comment]
Thanks @orthagh 
I guess I did too much copy-pasting.
It should be fixed.

**Comment by orthagh** [comment]
Plugin validated, it should be available in some minutes
