### ISSUE TITLE
Intégrer Tawk.to à GLPI

### ISSUE THREAD

**Issue by YunOoA** [ticgal/jsaddons#13]
<p><a href="https://github.com/ticgal/jsaddons/issues/13">https://github.com/ticgal/jsaddons/issues/13</a></p><p>Bonjour,</p><p>J'ai récemment ajouté le plugin JS Addons à GLPI et j'aurais aimé activer Tawk.to Je passe par l'onglet "configuration" -> JS Addons -> Tawk.to Je coche ensuite la case actif, mais le tchat ne s'affiche pas. Où puis-je trouver la clé qui est à renseigner ?</p><p>Bien cordialement</p><p><br />Created by YunOoA</p>
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_11121' rel='nofollow'>11121</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by gitsyncuser** [comment]
<p>Hi,</p><p>Sorry about my French.</p><p>Configuration on the tawk.to side is standard instructions: https://help.tawk.to/article/adding-a-widget-to-your-website</p><p>You just need the code.</p><p>This is not a bug so, I close.</p><p>Regards,</p><blockquote>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by YunOoA** [comment]
Bonjour, Hello,

Pour ceux qui chercherai à résoudre mon problème initial, j'ai trouvé la solution.
Le code Js doit être rajouté sur le code source de votre GLPI dans la partie plugin.
Rendez vous dans /var/www/glpi/marketplace/jsaddons/js/tawk to.js
Collez votre widget code à la place de celui présent dans le fichier.
ou
Modifiez la ligne sl.src uniquement.


For those who will seek to solve my initial problem, I found the solution.
The Js code must be added to the source code of your GLPI in the plugin part.
Go to /var/www/glpi/marketplace/jsaddons/js/tawk to.js
Paste your code widget in place of the one present in the file.
or
Edit the sl.src line only.


Cordialement

**Comment by OscarBeiro** [comment]
Not really.
If you'd added the tawk.to to the configuration, it would work without further tweaking.
This is the idea behind the plugin.
Regards,

**Comment by YunOoA** [comment]
Indeed,
I think I got it wrong during the configuration of the plugin. 
I didn't really understand which key to enter in GLPI but in the end the palliative solution suits me very well :)
Regards,
