### ISSUE TITLE
Google Analytics GA4

### ISSUE THREAD

**Issue by acremonezi** [ticgal/jsaddons#14]
Just find your plugin! Congratulations It is very usefull, clean and objective!

Could you Please Inform if its already for Google Analytics **GA4**?

Thanks and best regards!

**Comment by OscarBeiro** [comment]
Hi,
You just need to go to Setup > Activate Google Analytics and add the GA4 Property ID.
Regards,

**Comment by acremonezi** [comment]
Clear now!
Thanks and best regards!
