### ISSUE TITLE
Failed to authenticate with metricoo

### ISSUE THREAD

**Issue by miqonee** [ticgal/jsaddons#18]
Failed to authenticate with metricool after inserting a pixel, what could be the problem? 
![image](https://github.com/ticgal/jsaddons/assets/108046712/fefccefd-6101-4bd0-9bed-48200c0e6178)
this window has been weighing for several hours now, thanks.

**Comment by gitsyncuser** [comment]
<p>Hard to say with so little info.</p>\r\n<p>It is working. We use it on our GLPI:</p>\r\n<p><a href=\"/front/document.send.php?docid=41479&itemtype=Ticket&items_id=15408\" target=\"_blank\" ><img alt=\"10a52905-e509fb39-647e21b1c54c56.32498859\" width=\"1563\" src=\"/front/document.send.php?docid=41479&itemtype=Ticket&items_id=15408\" /></a></p>\r\n<p>Regards.</p>\r\n<p>Please use a clean GLPI 10.0.7 install and test again.</p>\r\n<p>Other than this report, your GLPI configuration: Setup &gt; General &gt; System</p>\r\n<p>And any Apache logs could help debugging if the request is coming from Metricool, or maybe you are blocking it somehow.</p>\r\n<p>Regards,</p><blockquote>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by OscarBeiro** [comment]
Cannot reproduce
