### ISSUE TITLE
CORS policy error

### ISSUE THREAD

**Issue by lexcorp** [ticgal/jsaddons#3]
Access to script at 'https://embed.tawk.to/5fe1f6d4df060f156a8f53bf/1eq5aobvg/default' from origin 'https://mydomain.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by OscarBeiro** [comment]
Hi Alexander,
This looks like a misconfigured tawk.to setup or a webserver issue. 
I have performed a quick google search and: https://community.cloudflare.com/t/cors-catching-is-not-allowed-by-access-control-allow-origin-error/89129
Not directly related to the plugin 

Cheers,
