### ISSUE TITLE
Integrate self-hosed Rocket.Chat

### ISSUE THREAD

**Issue by RAurelian** [ticgal/jsaddons#4]
Hello,
It would be useful to be able to integrate self-hosted RocketChat into GLPI using this plugin - is it possible? 
Thank you!

**Comment by OscarBeiro** [comment]
Hi,

A very entry-level integration could be possible. However, we don't have any Rocket.Chat instance or knowledge about this tool.
If you are willing to provide this information and means, we could work on it in the future.

However, Rocket.chat has an API so a better integration could be achieved.

Cheers,

**Comment by RAurelian** [comment]
Hi,
Thank you for the info. Unfortunately we cannot provide access to the in-house RC or GLPI instances, they need to remain internal. However, it`s extremely easy to to spin up a Rocket.Chat server using Ubuntu Snaps: https://snapcraft.io/rocketchat-server
We do not have programming capabilities, so we cannot make use of the APIs ourselves. We though that maybe a simple lightweight pop-up window integrated in GLPI would be the quickest way to an integration. But true, more advanced integration such as opening a ticket directly from RC or adding comments via chat would make a much better integration, but we do not have the knowledge for that at this time.
Best,
Aurelian

**Comment by OscarBeiro** [comment]
Hi Aurelian,

If you are willing to sponsor it, we can go either way: Simple or advanced integration, otherwise, we'll wait until we can get more feedback from any one using Rocket.Chat and GLPI.

Regards,

**Comment by RAurelian** [comment]
We've just started using GLPI amongst a few other tools as an evaluation to see if it can replace our current IT Helpdesk and asset management tool, so we're not 100% committed to it. Maybe if in the future GLPI will indeed prove the best in this respect, we might pursue this.

**Comment by OscarBeiro** [comment]
Hi Aurelian,
I see. Just consider we have the expertise to help you get the most of GLPI if you finally choose to go for it.
Cheers,

**Comment by RAurelian** [comment]
Thanks Oscar, we`ll definitely consider it.
