### ISSUE TITLE
JS Addons and  Tawk.to  not working

### ISSUE THREAD

**Issue by guillermohaad** [ticgal/jsaddons#5]
Hi
I have GLPI version 9.5.4 installed and integrated jsaddons and Tawk but it doesn't show me the chat.
 Tawk.to widget not  appear on the bottom right corner of GLPI.
Thank you

attached evidence configuration
![image](https://user-images.githubusercontent.com/12921805/113878249-0d04ef00-977f-11eb-8ded-eaa912da5725.png)

**Comment by guillermohaad** [comment]
hello any solution in this regard?
thank you

**Comment by danicouso** [comment]
Hello @guillermohaad, i just test in GLPi 9.5.5 and it works. Upgrade to GLPi 9.5.5. Greetings

![607868272dc214 29618430image_paste4302467](https://user-images.githubusercontent.com/75984175/114904165-dd598500-9e17-11eb-90a2-f74ac9634ecf.png)

**Comment by guillermohaad** [comment]
thank @danielcousosouto I will review with this version

**Comment by guillermohaad** [comment]
hi @danielcousosouto same problem v 9.5.5 ?
![image](https://user-images.githubusercontent.com/12921805/114947365-a339b480-9e12-11eb-8388-0f8d0676c033.png)

**Comment by danicouso** [comment]
Hi @guillermohaad , can you check the logs of GLPi? Please check if there are any errors specific to this plugin.

**Comment by guillermohaad** [comment]
@danielcousosouto hi any errors specific to this plugin? = nothing errors.

**Comment by gitsyncuser** [comment]
<p>Hi,</p><p>We cannot help you if no error is shown.  We are unable to replicate.</p><ol><li>Could you test it on a clean GLPI installation?</li><li>Could you test it on another webpage to see if it is something related to tawk.to?</li></ol><p>Regards,</p><blockquote>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by guillermohaad** [comment]
hi, @gitsyncuser 
Could you test it on a clean GLPI installation? yes , same problem
Could you test it on another webpage to see if it is something related to tawk.to? yes, working webpage

The only thing that is different is that in /glpi/plugin/  I don't see Js Addons installed

thank you

**Comment by danicouso** [comment]
Hi @guillermohaad , Same problem with clean GLPi 9.5.5 installation? Maybe the problem is in your browser, have you tried another?

**Comment by guillermohaad** [comment]
hi @danielcousosouto , I have tried in several browsers with the same result.

**Comment by danicouso** [comment]
Hi @guillermohaad, I don't know what could be happening. It works in my clean GLPi installation, I don't see any error in JS Addons and I can't help you. Greetings

**Comment by guillermohaad** [comment]
hi @danielcousosouto   please check https://sospymes.com/soporte/glpi/   
credentials ->   user: XXXXXX   passwd: XXXXXXXXX 

thank you

**Comment by danicouso** [comment]
Hi @guillermohaad, Sorry but with a selfservice user I can't see anything to diagnose the problem. Greetings

**Comment by guillermohaad** [comment]
hi @danielcousosouto , I gave the super permissions to this user so that you can try, thank you and stay tuned

**Comment by danicouso** [comment]
Hi @guillermohaad, I have login and I have already deleted the permissions for security. The plugin works for me, can you try again?


![609154fc7686d0 70039264image_paste8344814](https://user-images.githubusercontent.com/75984175/117016533-17b99200-acf3-11eb-9f40-81d6bb5da7b1.png)

**Comment by guillermohaad** [comment]
hi @danielcousosouto thanks solved... Please share with us why this happens what was i doing wrong??
