### ISSUE TITLE
Fuzzy instructions to integrate tawk.to with glpi

### ISSUE THREAD

**Issue by cgbermudezp** [ticgal/jsaddons#6]
<p><a href="https://github.com/ticgal/jsaddons/issues/6">https://github.com/ticgal/jsaddons/issues/6</a></p><p>Hello there. Instructions to integrate with glpi app. said: "Tawk.to Login to your tawk.to dashboard. Click on Administration, and choose the property you want to configure. Select Channels > Chat Widget.</p><p>On Direct Chat Link there is a URL with this structure tawk.to/chat/XXXXXXXXXXXXXXXXXXXXXXXX/XXXXXXX</p><p>Copy the string after tawk.to/chat/ <strong>and paste it to the Tawk.to form</strong>. Activate it. The Tawk.to widget will appear on the bottom right corner of GLPI."</p><p>Can you explain it better? Where is that form? This is the part I don't understand. Can you show some screenshots?</p><p>Regards.</p><p><br />Creado por cgbermudezp</p>
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_5915' rel='nofollow'>5915</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by gitsyncuser** [comment]
<p>Hi Carlos,</p><p>Thanks for trying JS Addons.</p><p>I have personally followed step by step the instructions and they are still valid.</p><p>If you have any Tawk.to related need, please contact Tawk.to support.</p><p>In case you need professional support regarding GLPI or any other plugin, please contact us.</p><p>Cheers,</p><blockquote>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>
